# Generated by Django 4.2.3 on 2023-07-20 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='garage',
            field=models.CharField(choices=[('none', 'No Garage'), ('Attached', 'Attached Garage'), ('Dettached', 'Dettached Garage')], default=None, max_length=10),
        ),
    ]
