agents = [
    {
        '_id': '1',
        'name': 'Lara Gibson',
        'email': 'laragibson@email.com',
        'phone': '+12029182132',
        'profile_photo': '/images/users/1.jpg',
        'bio': "Hello, I'm Lara Gibson, an experienced real estate agent with a proven track record. With over 10 years of industry expertise, I offer personalized service, tailored to meet each client's unique needs. I excel in negotiation and attention to detail, consistently achieving outstanding results. I stay current with industry advancements, utilizing cutting-edge tools and technology to implement effective marketing strategies for maximum listing exposure. ",
        'created_ad': '15.06.23',
        'updated_ad': '15.06.23',
        'twitter_link': 'https://www.twitter.com',
        'facebook_link': 'https://www.facebook.com',
        'linkedin_link': 'https://www.linkedin.com',
    },
    {
        '_id': '2',
        'name': 'Harrison Lewis',
        'email': 'harrisonlewis@email.com',
        'phone': '+15056445028',
        'profile_photo': '/images/users/2.jpg',
        'bio': "Hi, I'm Harrison Lewis, your dedicated real estate agent. With years of experience, I prioritize your needs and guide you through the process. I stay updated on market trends and use innovative strategies to attract buyers. Clear communication and transparency are my top priorities. Let's achieve your real estate goals together. Contact me today!",
        'created_ad': '13.06.23',
        'updated_ad': '16.06.23',

        'twitter_link': 'https://www.twitter.com',
        'facebook_link': 'https://www.facebook.com',
        'linkedin_link': 'https://www.linkedin.com',
    },
    {
        '_id': '3',
        'name': 'Austin Price',
        'email': 'austinprice@email.com',
        'phone': '+13037575798',
        'profile_photo': '/images/users/3.jpg',
        'bio': "Hey there, I'm Austin Price, your dedicated and results-driven real estate agent. I prioritize client satisfaction and provide a seamless experience tailored to your needs. With my extensive market knowledge, I guide buyers and sellers to make informed decisions. I excel in negotiations and always protect your interests. Let's connect and make your real estate dreams a reality. Contact me today!",
        'created_ad': '17.06.23',
        'updated_ad': '20.06.23',
        'twitter_link': 'https://www.twitter.com',
        'facebook_link': 'https://www.facebook.com',
        'linkedin_link': 'https://www.linkedin.com',
    },
    {
        '_id': '4',
        'name': 'Calvin Jackson',
        'email': 'calvinjackson@email.com',
        'phone': '+13238318234',
        'profile_photo': '/images/users/4.jpg',
        'bio': "Hi, I'm Calvin Jackson, your trusted real estate agent. With expert market knowledge, I guide clients through smart decisions. I excel in negotiations, ensuring your best interests are protected. Let's find your perfect home. Contact me, Calvin Jackson, today.",
        'created_ad': '11.06.23',
        'updated_ad': '15.06.23',
        'twitter_link': 'https://www.twitter.com',
        'facebook_link': 'https://www.facebook.com',
        'linkedin_link': 'https://www.linkedin.com',
    },
    {
        '_id': '5',
        'name': 'Theo Wallace',
        'email': 'theowallace@email.com',
        'phone': '+13077518266',
        'profile_photo': '/images/users/5.jpg',
        'bio': "Hey there, I'm Theo Wallace, your reliable real estate agent. With a focus on client satisfaction, I provide top-notch service tailored to your needs. Let's navigate the real estate market together and achieve your goals. Contact me, Theo Wallace, and let's get started.",
        'created_ad': '18.06.23',
        'updated_ad': '19.06.23',
        'twitter_link': 'https://www.twitter.com',
        'facebook_link': 'https://www.facebook.com',
        'linkedin_link': 'https://www.linkedin.com',
    },
    {
        '_id': '6',
        'name': 'Violet Carter',
        'email': 'violetcarter@email.com',
        'phone': '+12163560342',
        'profile_photo': '/images/users/6.jpg',
        'bio': "Hello, I'm Violet Carter, your dedicated real estate agent. With a passion for helping clients, I provide personalized service to meet your unique needs. Let's work together to find your dream property. Contact me, Violet Carter, and let's make your real estate dreams a reality.",
        'created_ad': '23.06.23',
        'updated_ad': '25.06.23',
        'twitter_link': 'https://www.twitter.com',
        'facebook_link': 'https://www.facebook.com',
        'linkedin_link': 'https://www.linkedin.com',
    },

]
