properties = [
    {
        '_id': '1',
        'state': 'Illinois',
        'city': 'Chicago',
        'address': '6437 S Normal Blvd, Chicago, IL 60621',
        'address_link': 'https://goo.gl/maps/uCxeXf5CKHNjd7KF8',
        'zip': '60621',
        'description': "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum. ",
        'image': '/images/houses/img1.webp',
        'bedrooms': '8',
        'bathrooms': '6',
        'garage': '2',
        'price': '219900',
        'year_build': '1905',
        'sqm': '288',
        'agent': 'Fiona Gallagher',
        'created_at': '12.06.2023',
    },
    {
        '_id': '2',
        'state': 'Illinois',
        'city': 'Chicago',
        'address': '2140 W 83rd St, Chicago, IL 60620',
        'address_link': 'https://goo.gl/maps/pVipbpZ7vF1ZT3Fb6',
        'zip': '60620',
        'description': "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum. ",
        'image': '/images/houses/img2.webp',
        'bedrooms': '3',
        'bathrooms': '2',
        'garage': '1',
        'price': '250000',
        'year_build': '1960',
        'sqm': '92',
        'agent': 'Philipp Gallagher',
        'created_at': '13.06.2023',
    },
    {
        '_id': '3',
        'state': 'Illinois',
        'city': 'Chicago',
        'address': '2660 N Orchard St, Chicago, IL 60614',
        'address_link': 'https://goo.gl/maps/5xhPobY6CdbasQSg7',
        'zip': '60614',
        'description': "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum. ",
        'image': '/images/houses/img3.webp',
        'bedrooms': '7',
        'bathrooms': '5',
        'garage': '2',
        'price': '2799000',
        'year_build': '2014',
        'sqm': '465',
        'agent': 'Debbie Gallagher',
        'created_at': '14.06.2023',
    },
    {
        '_id': '4',
        'state': 'New York',
        'city': 'Malverne',
        'address': '185 Wicks Ln, Malverne, NY 11565',
        'address_link': 'https://goo.gl/maps/XiPGAxfzeujjHzDc9',
        'zip': '11565',
        'description': "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum. ",
        'image': '/images/houses/img4.webp',
        'bedrooms': '3',
        'bathrooms': '2',
        'garage': '1    ',
        'price': '649000',
        'year_build': '1936',
        'sqm': '132',
        'agent': 'Yen Gallagher',
        'created_at': '15.06.2023',
    },
]
