const properties = [
    {
        '_id': '1',
        'state': 'Illinois',
        'city': 'Chicago',
        'address': '6437 S Normal Blvd, Chicago, IL 60621',
        'zip': '60621',
        'image': '/images/img1.webp',
        'bedrooms': '8',
        'bathrooms': '6',
        'garage': '2',
        'price': '219900',
        'year_build': '1905',
        'sqm': '288',
        'agent': 'Fiona Gallagher',
        'created_at': '12.06.2023',
    },
    {
        '_id': '2',
        'state': 'Illinois',
        'city': 'Chicago',
        'address': '2140 W 83rd St, Chicago, IL 60620',
        'zip': '60620',
        'image': '/images/img2.webp',
        'bedrooms': '3',
        'bathrooms': '2',
        'garage': '1',
        'price': '250000',
        'year_build': '1960',
        'sqm': '92',
        'agent': 'Philipp Gallagher',
        'created_at': '13.06.2023',
    },
    {
        '_id': '3',
        'state': 'Illinois',
        'city': 'Chicago',
        'address': '2660 N Orchard St, Chicago, IL 60614',
        'zip': '60614',
        'image': '/images/img3.webp',
        'bedrooms': '7',
        'bathrooms': '5',
        'garage': '2',
        'price': '2799000',
        'year_build': '2014',
        'sqm': '465',
        'agent': 'Debbie Gallagher',
        'created_at': '14.06.2023',
    },
    {
        '_id': '4',
        'state': 'New York',
        'city': 'Malverne',
        'address': '185 Wicks Ln, Malverne, NY 11565',
        'zip': '11565',
        'image': '/images/img4.webp',
        'bedrooms': '3',
        'bathrooms': '2',
        'garage': '1    ',
        'price': '649000',
        'year_build': '1936',
        'sqm': '132',
        'agent': 'Yen Gallagher',
        'created_at': '15.06.2023',
    },
    
]


export default properties